language: node_js

script:
  - chmod a+x build.sh
  - chmod a+x deploy.sh

  - npm run build
  - ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "d0f3b15271da"
  - COMMIT_AUTHOR_EMAIL: "zhukovsd@gmail.com"
